const BaseAgent = require('./baseAgent');

class GuruAgent extends BaseAgent {
  constructor() {
    super(
      'SEO Guru Agent', 
      'You are the iShack SEO Guru Agent. You are the ultimate authority on all SEO projects. You review the output of the Implementation and Backlink agents, verify them against iShack historic standards, and either approve them or assign re-work.'
    );
  }

  async executeTask(taskId, campaignId, payload) {
    await this.logThought(campaignId, 'Connecting to Google Drive memory stores via RAG index...', 'Aggregating historic template definitions.');
    
    const prompt = `Review the following work generated by the Sub-Agents. Does this meet high-quality agency standards? If yes, approve it. If not, detail exactly what the agent did wrong.`;
    
    const result = await this.think(prompt, payload);
    
    await this.logThought(campaignId, 'Review complete.', 'Reporting quality score back to the PM.');
    await this.completeTask(taskId, { review_feedback: result });
    
    return result;
  }
}

module.exports = new GuruAgent();
