const BaseAgent = require('./baseAgent');

class ImplementationAgent extends BaseAgent {
  constructor() {
    super(
      'Implementation Agent', 
      'You are the iShack SEO Implementation Agent. Your job is to take the Keyword Map generated by the Research Agent, and write highly optimized Title Tags, Meta Descriptions, and H1 tags. You are an expert copywriter with a focus on CTR and Semantic SEO.'
    );
  }

  async executeTask(taskId, campaignId, payload) {
    await this.logThought(campaignId, 'Ingesting Keyword strategy. Preparing to write onsite structural tags.', 'Drafting content blocks...');
    
    try {
      const prompt = `Using the following Keyword Map, generate a highly optimized Homepage Title Tag, Meta Description, and primary H1. Keep within standard pixel width limits. Output strictly as JSON.`;
      
      const result = await this.think(prompt, payload);
      const cleanRes = result.replace(/```json\n?|\n?```/g, '');
      
      await this.logThought(campaignId, 'Onsite implementation tags drafted successfully.', 'Submitting for approval.');
      await this.submitForApproval(taskId, JSON.parse(cleanRes));
    } catch (e) {
      console.error(e);
      await this.logThought(campaignId, `Execution Crash: ${e.message}`, `Failing Task`);
      await this.submitForApproval(taskId, { error: e.message });
    }
    
    return;
  }
}

module.exports = new ImplementationAgent();
